function [subjectID1,ankleFlexL1,ankleFlexR1,ankleVelL1,ankleVelR1,footVelL1,footVelR1,hipExtL1,hipExtR1,horizontalKL1,horizontalPL1,kneeFlexL1,kneeFlexR1,kneeVelL1,kneeVelR1,verticalKL1,verticalPL1] = importfileAccurateFile(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE1 Import data from a spreadsheet
%   [subjectID1,ankleFlexL1,ankleFlexR1,ankleVelL1,ankleVelR1,footVelL1,footVelR1,hipExtL1,hipExtR1,horizontalKL1,horizontalPL1,kneeFlexL1,kneeFlexR1,kneeVelL1,kneeVelR1,verticalKL1,verticalPL1]
%   = IMPORTFILE1(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as
%   column vectors.
%
%   [subjectID1,ankleFlexL1,ankleFlexR1,ankleVelL1,ankleVelR1,footVelL1,footVelR1,hipExtL1,hipExtR1,horizontalKL1,horizontalPL1,kneeFlexL1,kneeFlexR1,kneeVelL1,kneeVelR1,verticalKL1,verticalPL1]
%   = IMPORTFILE1(FILE,SHEET) reads from the specified worksheet.
%
%   [subjectID1,ankleFlexL1,ankleFlexR1,ankleVelL1,ankleVelR1,footVelL1,footVelR1,hipExtL1,hipExtR1,horizontalKL1,horizontalPL1,kneeFlexL1,kneeFlexR1,kneeVelL1,kneeVelR1,verticalKL1,verticalPL1]
%   = IMPORTFILE1(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   [subjectID1,ankleFlexL1,ankleFlexR1,ankleVelL1,ankleVelR1,footVelL1,footVelR1,hipExtL1,hipExtR1,horizontalKL1,horizontalPL1,kneeFlexL1,kneeFlexR1,kneeVelL1,kneeVelR1,verticalKL1,verticalPL1] = importfile1('soccer_accurate_data.xlsx','Sheet1',2,19);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2018/11/27 12:30:21

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 19;
end

%% Import the data
data = xlsread(workbookFile, sheetName, sprintf('A%d:Q%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    tmpDataBlock = xlsread(workbookFile, sheetName, sprintf('A%d:Q%d',startRow(block),endRow(block)));
    data = [data;tmpDataBlock]; %#ok<AGROW>
end

%% Allocate imported array to column variable names
subjectID1 = data(:,1);
ankleFlexL1 = data(:,2);
ankleFlexR1 = data(:,3);
ankleVelL1 = data(:,4);
ankleVelR1 = data(:,5);
footVelL1 = data(:,6);
footVelR1 = data(:,7);
hipExtL1 = data(:,8);
hipExtR1 = data(:,9);
horizontalKL1 = data(:,10);
horizontalPL1 = data(:,11);
kneeFlexL1 = data(:,12);
kneeFlexR1 = data(:,13);
kneeVelL1 = data(:,14);
kneeVelR1 = data(:,15);
verticalKL1 = data(:,16);
verticalPL1 = data(:,17);

